### ISSUE TITLE
Change file explorer icons

### ISSUE THREAD

**Issue by Doudom974** [Elhary/Obsidian-Minimal-Edge#3]
Hello,

First of all, I'd like to thank you very much for your theme. It's beautiful and will help me concentrate a lot.

I just have one question: how can I change the file explorer icons? I'd like to use ones that are more explicit in relation to my work.

1. I've tried the “Iconize” plugin, but instead of changing the icon, it adds another one to the left of the current icon!

2. I tried looking in the theme CSS, but couldn't figure out how to do it. (I'm a novice at this.)

Thank you very much for your work.

**Comment by Elhary** [comment]
Hi @Doudom974 

Thank you for your feedback! I'm glad you like the theme and I appreciate your suggestions. I’ve made the necessary changes based on your request. Please make sure to update the theme to the latest version to apply these changes.

1. **Update the Theme**:

  - First, go to the **Style Settings Plugin**.
  - Open **Minimal Edge** and toggle the interface.
  - Scroll down and find the **File Explorer Icon** section. Open it and toggle to hide the icons.
   
  Once the icons are hidden, you can use the **Iconize** plugin to apply custom icons.

## Manual CSS Customization
    
 If you'd like to manually adjust the CSS, follow these steps:
    
- open the CSS Snippets section.
- If you already have a CSS file, open it. If not, create a new one.
- Paste the following code into the CSS file:
        
```css

        .nav-folder .nav-folder-title .nav-folder-title-content::before {
            display: inline-block;
            width: 20px;
            height: 20px;
            background-size: 10px;
            content: "";
            font-size: 1rem;
            mask-image: url(""); /* Replace this with your icon's Data URL */
            mask-repeat: no-repeat;
            mask-position: center;
        }
        
        .nav-folder.is-collapsed .nav-folder-title .nav-folder-title-content::before {
            mask-image: url(""); /* Replace this with your icon's Data URL */
            mask-repeat: no-repeat;
            mask-position: center;
        }
        
        .nav-file .nav-file-title-content:before {
            content: "";
            position: relative;
            mask-image: url(""); /* Replace this with your icon's Data URL */
            mask-repeat: no-repeat;
            mask-position: center;
            display: inline-block;
            margin-right: 4px;
            height: 14px;
            width: 14px;
        }
```


    
    
To change the icon, replace the `mask-image: url("");` with your own icon URL. To get the icon URL, you need to convert the SVG to a Data URL.

I recommend using [SVGViewer](https://www.svgviewer.dev/svg-to-data-uri?utm_source=chatgpt.com) for easy conversion.
    
in SVGViweer Paste your SVG code into the editor, then copy the URL on the right side.

![Image](https://github.com/user-attachments/assets/8d9a6ad7-7327-4703-9399-e3b4a867dacf)

make sure to remove the height and width attributes from the SVG code. This will allow you to change the icon's size directly through CSS.

![Image](https://github.com/user-attachments/assets/d74188b7-d56c-4990-82e5-d08965552f62)

If you have any more questions, feel free to reach out. Thanks again for your feedback!

**Comment by Doudom974** [comment]
Hello @Elhary 

Thank you very much for your quick response and the help!
It was perfect! I have to admit, I took the easy way out and used iconize. Everything works fine. And thanks for the step-by-step guide, it helps me understand how it all works! (I'm also new to Obsidian)

A small suggestion to improve the theme.
On my Mac, when I put Obsidian on the big screen, the background of the icon in the top right-hand corner changes to a white background (see the red circle in the image).


<img width="595" alt="Image" src="https://github.com/user-attachments/assets/b975a115-58c4-4a07-baf2-1fb37ecee80a" />

And a little something of my own:
Still in the file explorer, it would be nice to be able to bold the names of folders in relation to notes or files. I think it would clarify the organisation, but that's just my opinion. (I imagine I could do it via a snippet...)

Many thanks again for your help to the community.

**Comment by Elhary** [comment]
I’m glad to hear the Iconize plugin worked well for you.  

I’ll look into the top-right icon background issue on larger screens and consider your suggestion about bolding folder names to enhance clarity.  

In the meantime, if you’d like to implement this yourself, you can use the following snippet in your CSS:  

```css  
.nav-file-title, .nav-folder-title {  
   font-size: 13px;  
   font-weight: 400; /* Adjust to 500, 700, or 800 if needed */  
}  
```  

thanks again for your feedback! Feel free to reach out anytime.
